Repository HI-dle/rouby, pull requests merged in 2025-09, with the labels that each got.

#218 [#96][fe][notification] 알림 설정 및 이벤트 핸들링 보완
  front/public/firebase-messaging-sw.js
  front/src/App.vue
  front/src/components/common/ToastCard.vue
  front/src/features/onboard/views/OnboardNicknameSettingView.vue
  front/src/main.js
  front/src/shared/composable/useToast.js
  front/src/shared/firebase/config.js
Labels: ✨ feature, 🎨 frontend, ♻️ refactor

#219 [#96][be][notification] 알림 전송 코드 보완
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/messaging/fcm/FcmMessageHelper.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/messaging/fcm/FirebaseNotificationSender.java
  back/src/main/java/com/rouby/user/device/domain/entity/UserDevice.java
  back/src/main/resources/properties/base.yml
Labels: ♻️ refactor, 🛠️ backend

#208 [#194][be][assistant] 브리핑 배치 생성 구현
  back/build.gradle
  back/src/main/java/com/rouby/assistant/briefing/application/facade/BriefingFacade.java
  back/src/main/java/com/rouby/assistant/briefing/application/service/BriefingService.java
  back/src/main/java/com/rouby/assistant/briefing/domain/repository/BriefingRepository.java
  back/src/main/java/com/rouby/assistant/briefing/infrastructure/persistence/jpa/BriefingJpaRepository.java
  back/src/main/java/com/rouby/assistant/prompt/application/client/BriefingClient.java
  back/src/main/java/com/rouby/assistant/prompt/application/service/PromptReadService.java
  back/src/main/java/com/rouby/assistant/prompt/infrastructure/ai/GeminiAiClient.java
  back/src/main/java/com/rouby/batch/QuartzBriefingJob.java
  back/src/main/java/com/rouby/batch/job/config/BatchConfig.java
  back/src/main/java/com/rouby/batch/job/config/QuartzConfig.java
  back/src/main/java/com/rouby/batch/job/step/BriefingProcessor.java
  back/src/main/java/com/rouby/batch/job/step/BriefingReader.java
  back/src/main/java/com/rouby/batch/job/step/BriefingWriter.java
  back/src/main/java/com/rouby/common/utils/JsonHelper.java
  back/src/main/java/com/rouby/notification/notificationEvent/application/service/NotificationEventWriteService.java
  back/src/main/java/com/rouby/routine/routine_task/application/dto/info/RoutineTaskSummaryInfo.java
  back/src/main/java/com/rouby/routine/routine_task/application/service/RoutineTaskReadService.java
  back/src/main/java/com/rouby/schedule/application/dto/info/SchedulesSummaryInfo.java
  back/src/main/java/com/rouby/schedule/application/service/ScheduleReadService.java
  back/src/main/java/com/rouby/user/user/application/dto/info/UserInfo.java
  back/src/main/java/com/rouby/user/user/application/service/UserReadService.java
  back/src/main/java/com/rouby/user/user/domain/repository/UserRepository.java
  back/src/main/java/com/rouby/user/user/infrastructure/persistence/jpa/UserJpaRepository.java
  back/src/main/java/com/rouby/user/user/infrastructure/persistence/jpa/UserJpaRepositoryCustom.java
  back/src/main/java/com/rouby/user/user/infrastructure/persistence/jpa/UserJpaRepositoryCustomImpl.java
  back/src/main/resources/application.yml
  back/src/main/resources/properties/ai.yml
  back/src/main/resources/properties/batch.yml
  back/src/main/resources/properties/datasource.yml
  back/src/main/resources/properties/quartz.yml
Labels: ✨ feature, 🛠️ backend

#225 [#96][fe][notification] 누락한 코드래빗 리뷰 반영
  front/public/firebase-messaging-sw.js
  front/src/components/common/ToastCard.vue
  front/src/shared/composable/useToast.js
  front/src/shared/firebase/config.js
  front/src/shared/utils/linkUtils.js
Labels: 🎨 frontend, ♻️ refactor

#227 [#226][fe][schedule] 일정 조회 및 생성 후 재조회 로직 수정
  front/package-lock.json
  front/src/features/auth/authService.js
  front/src/features/schedule/useScheduleForm.js
  front/src/features/schedule/useScheduleList.js
  front/src/shared/utils/rruleUtils.js
  front/src/stores/useAuthStore.js
  front/src/stores/useDatePickStore.js
  front/src/stores/useScheduleStore.js
Labels: 🎨 frontend, ♻️ refactor

#223 [#222][be][notification] 알림 생성 및 조회 추가
  back/src/main/java/com/rouby/notification/notificationtemplate/application/dto/command/CreateNotificationTemplateCommand.java
  back/src/main/java/com/rouby/notification/notificationtemplate/application/dto/query/NotificationMessageQuery.java
  back/src/main/java/com/rouby/notification/notificationtemplate/application/exception/NotificationTemplateErrorCode.java
  back/src/main/java/com/rouby/notification/notificationtemplate/application/exception/NotificationTemplateException.java
  back/src/main/java/com/rouby/notification/notificationtemplate/application/facade/NotificationTemplateFacade.java
  back/src/main/java/com/rouby/notification/notificationtemplate/application/service/NotificationTemplateReadService.java
  back/src/main/java/com/rouby/notification/notificationtemplate/application/service/NotificationTemplateWriteService.java
  back/src/main/java/com/rouby/notification/notificationtemplate/domain/entity/Message.java
  back/src/main/java/com/rouby/notification/notificationtemplate/domain/entity/NotificationTemplate.java
  back/src/main/java/com/rouby/notification/notificationtemplate/domain/repository/NotificationTemplateRepository.java
  back/src/main/resources/db/insert-template.sql
  back/src/main/resources/properties/datasource.yml
Labels: ✨ feature, 🛠️ backend

#230 [#210][be][assistant]배치 비동기 및 알람 이벤트 추가
  back/build.gradle
  back/src/main/java/com/rouby/assistant/briefing/application/dto/info/CreatedBriefingResult.java
  back/src/main/java/com/rouby/assistant/briefing/application/facade/BriefingFacade.java
  back/src/main/java/com/rouby/assistant/briefing/domain/repository/BriefingRepository.java
  back/src/main/java/com/rouby/batch/QuartzBriefingJob.java
  back/src/main/java/com/rouby/batch/config/BatchConfig.java
  back/src/main/java/com/rouby/batch/config/QuartzConfig.java
  back/src/main/java/com/rouby/batch/job/briefing/dto/BriefingAggregate.java
  back/src/main/java/com/rouby/batch/job/briefing/dto/BriefingNotificationEvents.java
  back/src/main/java/com/rouby/batch/job/briefing/dto/UserBriefingInfo.java
  back/src/main/java/com/rouby/batch/job/briefing/step/BriefingProcessor.java
  back/src/main/java/com/rouby/batch/job/briefing/step/BriefingReader.java
  back/src/main/java/com/rouby/batch/job/briefing/step/BriefingWriter.java
  back/src/main/java/com/rouby/batch/job/config/BatchConfig.java
  back/src/main/java/com/rouby/batch/job/step/BriefingProcessor.java
  back/src/main/java/com/rouby/batch/job/step/BriefingReader.java
  back/src/main/java/com/rouby/batch/job/step/BriefingWriter.java
  back/src/main/java/com/rouby/common/utils/PerformanceAspect.java
  back/src/main/java/com/rouby/notification/notificationEvent/application/facade/NotificationEventFacade.java
  back/src/main/java/com/rouby/notification/notificationEvent/application/service/NotificationEventWriteService.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/entity/DeviceTokenInfo.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/entity/NotificationEvent.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/entity/NotificationMessage.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/repository/NotificationEventRepository.java
  back/src/main/java/com/rouby/user/device/application/dto/command/GetUserDeviceQuery.java
  back/src/main/java/com/rouby/user/device/application/exception/UserDeviceErrorCode.java
  back/src/main/java/com/rouby/user/device/application/scheduler/UserDeviceScheduler.java
  back/src/main/java/com/rouby/user/device/application/service/UserDeviceReadService.java
  back/src/main/java/com/rouby/user/device/application/service/UserDeviceWriteService.java
  back/src/main/java/com/rouby/user/device/domain/repository/UserDeviceRepository.java
  back/src/main/java/com/rouby/user/user/domain/repository/UserRepository.java
  back/src/main/resources/db/insert-template.sql
  back/src/main/resources/properties/quartz.yml
Labels: ♻️ refactor, 🛠️ backend

#232 [#53][be][assistant] 브리핑 조회 추가
  back/src/docs/asciidoc/briefing.adoc
  back/src/main/java/com/rouby/assistant/briefing/application/dto/info/BriefingInfo.java
  back/src/main/java/com/rouby/assistant/briefing/application/exception/BriefingErrorCode.java
  back/src/main/java/com/rouby/assistant/briefing/application/facade/BriefingFacade.java
  back/src/main/java/com/rouby/assistant/briefing/application/service/BriefingReadService.java
  back/src/main/java/com/rouby/assistant/briefing/application/service/BriefingService.java
  back/src/main/java/com/rouby/assistant/briefing/domain/repository/BriefingRepository.java
  back/src/main/java/com/rouby/assistant/briefing/infrastructure/persistence/jpa/BriefingJpaRepositoryCustom.java
  back/src/main/java/com/rouby/assistant/briefing/infrastructure/persistence/jpa/BriefingJpaRepositoryCustomImpl.java
  back/src/main/java/com/rouby/assistant/briefing/presentation/BriefingController.java
  back/src/main/java/com/rouby/assistant/briefing/presentation/dto/response/BriefingResponse.java
  back/src/test/java/com/rouby/assistant/briefing/BriefingControllerTest.java
  back/src/test/java/com/rouby/common/support/ControllerTestSupport.java
Labels: ✨ feature, 🛠️ backend

#236 [#58][fe][assistant] 브리핑 화면 추가
  front/src/features/assistant/api.js
  front/src/features/assistant/assistantService.js
  front/src/features/assistant/component/BriefingForm.vue
  front/src/features/assistant/useBriefingForm.js
  front/src/features/assistant/views/BriefingLayout.vue
  front/src/features/assistant/views/DailyBriefingView.vue
  front/src/router/index.js
Labels: ✨ feature, 🎨 frontend

#237 [#229][be][notification] 알림 배치 전송 서비스 구현
  back/build.gradle
  back/src/main/java/com/rouby/assistant/briefing/application/facade/BriefingFacade.java
  back/src/main/java/com/rouby/batch/briefing/BriefingBatchConfig.java
  back/src/main/java/com/rouby/batch/briefing/BriefingQuartzJob.java
  back/src/main/java/com/rouby/batch/briefing/dto/BriefingAggregate.java
  back/src/main/java/com/rouby/batch/briefing/dto/BriefingNotificationEvents.java
  back/src/main/java/com/rouby/batch/briefing/dto/UserBriefingInfo.java
  back/src/main/java/com/rouby/batch/briefing/step/BriefingProcessor.java
  back/src/main/java/com/rouby/batch/briefing/step/BriefingReader.java
  back/src/main/java/com/rouby/batch/briefing/step/BriefingWriter.java
  back/src/main/java/com/rouby/batch/config/QuartzConfig.java
  back/src/main/java/com/rouby/batch/notification/DbWriterAdapter.java
  back/src/main/java/com/rouby/batch/notification/DefaultDispatcher.java
  back/src/main/java/com/rouby/batch/notification/NotificationDispatcher.java
  back/src/main/java/com/rouby/batch/notification/NotificationQuartzJob.java
  back/src/main/java/com/rouby/batch/notification/ResultWriter.java
  back/src/main/java/com/rouby/batch/notification/config/DispatcherThreadConfig.java
  back/src/main/java/com/rouby/common/config/TimeConfig.java
  back/src/main/java/com/rouby/common/config/WebClientConfig.java
  back/src/main/java/com/rouby/notification/notificationEvent/application/dto/CreateNotificationEventCommand.java
  back/src/main/java/com/rouby/notification/notificationEvent/application/service/NotificationEventWriteService.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/entity/NotificationEvent.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/entity/NotificationType.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/entity/SendStatus.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/info/NotificationEventInfo.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/info/SuccessResult.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/repository/NotificationEventRepository.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/sender/AsyncNotificationSender.java
  back/src/main/java/com/rouby/notification/notificationEvent/domain/sender/NotificationSender.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/exception/NotificationEventFcmException.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/exception/NotificationEventFcmRetryableException.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/messaging/fcm/FcmConfiguration.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/messaging/fcm/FcmMessageHelper.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/messaging/fcm/FcmSender.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/messaging/fcm/GoogleAccessTokenProvider.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/messaging/fcm/WebClientFcmSender.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/persistence/NotificationEventRepositoryImpl.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/persistence/jdbc/NotificationEventJdbcRepository.java
  back/src/main/java/com/rouby/notification/notificationEvent/infrastructure/persistence/jpa/NotificationEventJpaRepository.java
  back/src/main/resources/application.yml
  back/src/main/resources/db/schema.sql
  back/src/main/resources/properties/firebase.yml
  back/src/main/resources/properties/notification-worker.yml
  back/src/main/resources/properties/resilience.yml
  back/src/test/http/notification-event.http
Labels: ✨ feature, 🛠️ backend
